/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.casitaprojects.parkpluss;

import java.awt.Dimension;
import java.io.IOException;
import main.java.com.casitaprojects.parkpluss.TipoArea;
import main.java.com.casitaprojects.parkpluss.TipoVehiculo;
import main.java.com.casitaprojects.parkpluss.RegistroEntrada;
/**
 *
 * @author gezer
 */
public class panelingresarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form panelingresarVehiculo
     */
    public panelingresarVehiculo() {
        initComponents();
        setPreferredSize(new Dimension(895, 495));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdbMoto = new javax.swing.JRadioButton();
        rdbAuto = new javax.swing.JRadioButton();
        chboxEstudiante = new javax.swing.JCheckBox();
        chboxCatedrático = new javax.swing.JCheckBox();
        rdbFlat = new javax.swing.JRadioButton();
        rdbVariable = new javax.swing.JRadioButton();
        btnIngresar = new javax.swing.JButton();

        jLabel1.setText("INGRESO DE VEHICULOS AL PARQUEO");

        jLabel2.setText("PLACA");

        jLabel3.setText("NOMBRE PROPIETARIO");

        jLabel4.setText("TIPO DE VEHICULO");

        buttonGroup3.add(rdbMoto);
        rdbMoto.setText("Motocicleta");

        buttonGroup3.add(rdbAuto);
        rdbAuto.setText("Automovil");
        rdbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAutoActionPerformed(evt);
            }
        });

        buttonGroup1.add(chboxEstudiante);
        chboxEstudiante.setText("ESTUDIANTE");

        buttonGroup1.add(chboxCatedrático);
        chboxCatedrático.setText("CATEDRATICO");
        chboxCatedrático.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxCatedráticoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbFlat);
        rdbFlat.setText("FLAT");

        buttonGroup2.add(rdbVariable);
        rdbVariable.setText("VARIABLE");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rdbFlat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbVariable))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chboxEstudiante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chboxCatedrático))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbMoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbAuto))
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMoto)
                    .addComponent(rdbAuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chboxEstudiante)
                    .addComponent(chboxCatedrático))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbVariable)
                    .addComponent(rdbFlat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAutoActionPerformed

    private void chboxCatedráticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxCatedráticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxCatedráticoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    String placa = txtPlaca.getText().trim();

    // 🔹 Tipo de vehículo
    TipoVehiculo tipoVehiculo = null;
    if (rdbMoto.isSelected()) {
        tipoVehiculo = TipoVehiculo.MOTO;
    } else if (rdbAuto.isSelected()) {
        tipoVehiculo = TipoVehiculo.AUTO;
    }

    // 🔹 Tipo de área
    TipoArea tipoArea = null;
    if (chboxEstudiante.isSelected()) {
        tipoArea = TipoArea.ESTUDIANTES;
    } else if (chboxCatedrático.isSelected()) {
        tipoArea = TipoArea.CATEDRATICOS;
    }

    // 🚫 Validaciones
    if (placa.isEmpty() || tipoVehiculo == null || tipoArea == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "⚠️ Debes llenar todos los campos.");
        return;
    }

    // 🔹 Selección del modo de cobro
    String[] opciones = {"FLAT (Q10.00)", "VARIABLE (Q5/hora)"};
    int seleccion = javax.swing.JOptionPane.showOptionDialog(
            this,
            "Selecciona el modo de cobro:",
            "Modo de Tarifa",
            javax.swing.JOptionPane.DEFAULT_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
    );

    ModoTarifa modoSeleccionado;
    if (seleccion == 1) {
        modoSeleccionado = ModoTarifa.VARIABLE;
    } else if (seleccion == 0) {
        modoSeleccionado = ModoTarifa.FLAT;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Operación cancelada.");
        return;
    }

    // 🟢 Crear objeto Vehículo y guardarlo
    Vehiculo nuevoVehiculo = new Vehiculo(placa, tipoVehiculo, tipoArea);
    nuevoVehiculo.guardarEnCSV();

    // 🟢 Registrar el ingreso (ahora enviamos el modoTarifa)
    RegistroEntrada.registrarVehiculo(nuevoVehiculo, modoSeleccionado);

    // 🔹 Actualizar capacidad del área correspondiente
    try {
        String areaId = "";
        if (tipoVehiculo == TipoVehiculo.MOTO) {
            areaId = "A01"; // Motos
        } else if (tipoArea == TipoArea.ESTUDIANTES) {
            areaId = "A02"; // Autos Estudiantes
        } else if (tipoArea == TipoArea.CATEDRATICOS) {
            areaId = "A03"; // Autos Catedráticos
        }

        GestorCSV.actualizarCapacidadArea(areaId, true); // true = ocupar
    } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "❌ Error al actualizar la capacidad del área: " + e.getMessage());
    }

    // ✅ Mensaje final
    javax.swing.JOptionPane.showMessageDialog(this, 
        "✅ Vehículo ingresado correctamente.\nPlaca: " + placa);

    // 🧹 Limpiar campos
    txtPlaca.setText("");
    txtNombre.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    buttonGroup3.clearSelection();

    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox chboxCatedrático;
    private javax.swing.JCheckBox chboxEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdbAuto;
    private javax.swing.JRadioButton rdbFlat;
    private javax.swing.JRadioButton rdbMoto;
    private javax.swing.JRadioButton rdbVariable;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
