/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.casitaprojects.parkpluss;

import java.awt.Dimension;

/**
 *
 * @author gezer
 */
public class panelRetirarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form panelRetirarVehiculo
     */
    public panelRetirarVehiculo() {
        initComponents();
        setPreferredSize(new Dimension(895, 495));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        btnRetirarF = new javax.swing.JButton();

        jLabel1.setText("SALIDA DE VEHICULOS DEL PARQUEO");

        jLabel2.setText("PLACA");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        btnRetirar.setText("RETIRAR"); // NOI18N
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnRetirarF.setText("RETIRAR FLAT");
        btnRetirarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetirarF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetirarF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
    String placa = txtPlaca.getText().trim();

    if (placa.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "⚠️ Debes ingresar una placa para retirar.");
        return;
    }

    // 🔹 Llamar al proceso de retiro (esto debe devolverte el ticket)
    Ticket ticket = RegistroEntrada.retirarVehiculo(placa);

    // 🔹 Validar si se encontró un ticket
    if (ticket == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "❌ No se encontró un ticket activo para la placa: " + placa);
        return;
    }

    // 🔹 Cerrar el ticket (registrar salida y monto)
    ticket.cerrarTicket();

    // 🔹 Asegurar que si es FLAT tenga monto fijo Q10 después del cierre
    if (ticket.getModoTarifa() == ModoTarifa.FLAT) {
        ticket.setMonto(10.00);
    }

    // 🔹 Generar factura PDF con el monto correcto
    ticket.generarTicketPDF();
    GestorDB.actualizarTicketSalida(ticket);
    // 🔹 Mostrar mensaje con el monto total
    javax.swing.JOptionPane.showMessageDialog(this, 
        "✅ Vehículo retirado correctamente.\n" +
        "Monto total a pagar: Q" + String.format("%.2f", ticket.getMonto()));

    txtPlaca.setText("");

    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnRetirarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarFActionPerformed
            String placa = txtPlaca.getText().trim();

    if (placa.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Ingresa una placa.");
        return;
    }

    Ticket ticket = RegistroEntrada.retirarVehiculo(placa);
    if (ticket == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "❌ No hay ticket activo para esa placa.");
        return;
    }

    // Validar que realmente sea FLAT
    if (ticket.getModoTarifa() != ModoTarifa.FLAT) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Esta opción solo aplica a tickets FLAT.");
        return;
    }

    // Asignar cobro fijo
    ticket.setMonto(10.00);
    ticket.cerrarTicket();
    ticket.generarTicketPDF();

    // Registrar derecho a reingreso por 2 horas
    RegistroEntrada.marcarReingresoTemporal(ticket, 2);
    
    GestorDB.actualizarTicketSalida(ticket);
    GestorDB.insertarReingreso(ticket, 2);

    javax.swing.JOptionPane.showMessageDialog(this,
        "🚗 Vehículo FLAT retirado correctamente.\n" +
        "Monto: Q10.00\n" +
        "Tiene derecho a reingresar dentro de 2 horas sin nuevo cobro.");

    txtPlaca.setText("");

    }//GEN-LAST:event_btnRetirarFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetirarF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
