/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.casitaprojects.parkpluss;

/**
 *
 * @author gezer
 */

import java.sql.Connection;
import javax.swing.*;
import java.awt.*;
import java.time.LocalDateTime;
import main.java.com.casitaprojects.parkpluss.ConexionDB;



public class Parqueo extends javax.swing.JFrame {
    
    panelingresarVehiculo panelingresarvehiculo;
    panelRetirarVehiculo panelRetirarvehiculo;
    panelBuscarVehiculo panelBuscarvehiculo;
    
    JPanel panelContenido;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Parqueo.class.getName());

    
    public Parqueo() {
        initComponents();
        // *** LLAMADA AL NUEVO MÉTODO PARA CARGAR EL ICONO ESCALADO ***
        cargarIcono();
        // ***************************************************************
        
        getContentPane().setLayout(new BorderLayout());
        add(jpPrincipal, BorderLayout.WEST);
        getContentPane().setLayout(new BorderLayout());
        add(jpPrincipal, BorderLayout.WEST);
        
         panelContenido = new JPanel(new CardLayout());
         panelContenido.setPreferredSize(new java.awt.Dimension(895, 495));
         panelContenido.setMinimumSize(new Dimension(895, 495));
         panelContenido.setMaximumSize(new Dimension(895, 495));
        add(panelContenido, BorderLayout.CENTER);
        
        panelingresarvehiculo = new panelingresarVehiculo();
        panelRetirarvehiculo = new panelRetirarVehiculo();
        panelBuscarvehiculo = new panelBuscarVehiculo();
        
        JPanel panelVacio = new JPanel();
        panelVacio.setBackground(Color.WHITE); 
        panelContenido.add(panelVacio, "BLANCO");

        panelContenido.add(panelingresarvehiculo, "INGRESAR");
        panelContenido.add(panelRetirarvehiculo, "RETIRAR");
        panelContenido.add(panelBuscarvehiculo, "BUSCAR");
        
        CardLayout cl = (CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, "BLANCO");
        
        setSize(1000, 600);
        setLocationRelativeTo(null);
        setTitle("ParkPluss - Sistema de Parqueo");
        
    }
    
    private void mostrarPanel(String nombrePanel) {
        CardLayout cl = (CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, nombrePanel);
        
    }
    
    private void cargarIcono() {
    // Dimensiones del JLabel 'lblIcono'
    final int ICON_WIDTH = 120;
    final int ICON_HEIGHT = 96;
    
    // *** RUTA CORREGIDA: Sin el slash inicial ni la carpeta 'img' ***
    // Java buscará este archivo en el mismo paquete de la clase Parqueo.
    final String ICON_PATH = "istockphoto-1622168072-612x612.jpg"; // ¡Cambio clave aquí! 

    try {
        // Usamos la clase Parqueo para asegurar la búsqueda dentro de su paquete
        java.net.URL imgURL = Parqueo.class.getResource(ICON_PATH);
        
        if (imgURL == null) {
            System.err.println("Error: No se pudo encontrar el icono en la ruta: " + ICON_PATH);
            lblIcono.setText("Icono NO encontrado");
            return;
        }

        ImageIcon originalIcon = new ImageIcon(imgURL);
        Image imagenOriginal = originalIcon.getImage();
        
        // Escala la imagen a 120x96
        Image imagenEscalada = imagenOriginal.getScaledInstance(
            ICON_WIDTH, 
            ICON_HEIGHT, 
            Image.SCALE_SMOOTH
        );

        // Asigna y limpia el texto
        lblIcono.setIcon(new ImageIcon(imagenEscalada));
        lblIcono.setText(""); 
        
    } catch (Exception ex) {
        System.err.println("Error al procesar el icono: " + ex.getMessage());
        lblIcono.setText("Error Icono");
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        btnIngresarVehiculo = new java.awt.Button();
        btnRetirarVehiculo = new java.awt.Button();
        btnBuscarVehiculo = new java.awt.Button();
        btnSalir = new java.awt.Button();
        btnReingreso = new javax.swing.JButton();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        jpPrincipal.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ParkPluss");

        lblIcono.setText("jLabel2");

        btnIngresarVehiculo.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btnIngresarVehiculo.setLabel("Ingresar Vehiculo");
        btnIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVehiculoActionPerformed(evt);
            }
        });

        btnRetirarVehiculo.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btnRetirarVehiculo.setLabel("Retirar Vehiculo");
        btnRetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarVehiculoActionPerformed(evt);
            }
        });

        btnBuscarVehiculo.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btnBuscarVehiculo.setLabel("Buscar Vehiculo");
        btnBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btnSalir.setLabel("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReingreso.setText("Reingreso");
        btnReingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReingresoActionPerformed(evt);
            }
        });

        button1.setLabel("IMPORTAR DATOS A BD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetirarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVehiculoActionPerformed
         mostrarPanel("INGRESAR");
    }//GEN-LAST:event_btnIngresarVehiculoActionPerformed

    private void btnRetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarVehiculoActionPerformed
        mostrarPanel("RETIRAR");
    }//GEN-LAST:event_btnRetirarVehiculoActionPerformed

    private void btnBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculoActionPerformed
        mostrarPanel("BUSCAR");
    }//GEN-LAST:event_btnBuscarVehiculoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReingresoActionPerformed
String placa = JOptionPane.showInputDialog(this, "Ingrese la placa del vehículo:");

    if (placa == null || placa.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ Debes ingresar una placa.");
        return;
    }

Ticket ultimo = RegistroEntrada.buscarTicketPorPlaca(placa.trim());
if (ultimo == null) {
    JOptionPane.showMessageDialog(this, "❌ No se encontró ningún registro anterior de esa placa.");
    return;
}

if (ultimo.getModoTarifa() != ModoTarifa.FLAT) {
    JOptionPane.showMessageDialog(this, "⚠️ Este vehículo no tiene modo FLAT.");
    return;
}

if (ultimo.getFechaSalida() == null) {
    JOptionPane.showMessageDialog(this, "⚠️ El vehículo aún está activo dentro del parqueo.");
    return;
}

    // Verificamos que el ticket tenga modo FLAT
    if (ultimo.getModoTarifa() == ModoTarifa.FLAT) {

        // Si el ticket no tiene fecha de salida, significa que aún está activo
        if (ultimo.getFechaSalida() == null) {
            JOptionPane.showMessageDialog(this,
                "🚗 El vehículo aún está dentro del parqueo.\nNo se puede registrar reingreso.");
            return;
        }

        // Calculamos el tiempo desde la última salida
        LocalDateTime salida = ultimo.getFechaSalida();
        long minutos = java.time.Duration.between(salida, LocalDateTime.now()).toMinutes();

        if (minutos <= 120) {
            JOptionPane.showMessageDialog(this,
                "✅ Reingreso válido: aún dentro del tiempo del ticket FLAT.\nNo se cobrará nuevamente.");

            Vehiculo v = new Vehiculo(placa.trim(), TipoVehiculo.AUTO, TipoArea.ESTUDIANTES);
            RegistroEntrada.registrarVehiculo(v, ModoTarifa.FLAT);
            return;

        } else {
            JOptionPane.showMessageDialog(this,
                "⌛ Tiempo del ticket FLAT expirado. Se generará un nuevo cobro.");
            Vehiculo v = new Vehiculo(placa.trim(), TipoVehiculo.AUTO, TipoArea.ESTUDIANTES);
            Ticket nuevoTicket = RegistroEntrada.registrarVehiculo(v, ModoTarifa.FLAT);
            if(nuevoTicket != null){
                GestorDB.insertarTicket(nuevoTicket);
            }
            return;
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "⚠️ Este vehículo no tiene tarifa FLAT registrada.");
    }

    }//GEN-LAST:event_btnReingresoActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        CSVtoDatabaseImporter importer = new CSVtoDatabaseImporter();
        importer.importarTodo();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Parqueo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBuscarVehiculo;
    private java.awt.Button btnIngresarVehiculo;
    private javax.swing.JButton btnReingreso;
    private java.awt.Button btnRetirarVehiculo;
    private java.awt.Button btnSalir;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblIcono;
    // End of variables declaration//GEN-END:variables
}
